#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Only run this script as root."
  exit
fi

# -------------------------------------------------------------------------------------------------
echo
echo `date`
echo "Deleting vhost ..."
# -------------------------------------------------------------------------------------------------

# Output a usage message - used when the parameters input are not correct.
usage () {
    echo "Usage: `basename "$0"` -n <name of the web-app instance> -u <web-app user account>"
}

# -------------------------------------------------------------------------------------------------
# Testing parameter(s)
# -------------------------------------------------------------------------------------------------
while getopts ":n:u:" opt; do
    case $opt in
        n)
            SUPPLIED_NAME=$OPTARG
            ;;
        u)
            WEB_APP_USER=$OPTARG
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            usage
            exit 1
            ;;
    esac
done

# Check required parameters have had values assigned.
if [ -z $SUPPLIED_NAME ] || [ -z $WEB_APP_USER ]
then
    echo "The web-app name and web-app user need to be provided as parameters on the command line."
    usage
    exit 1
fi

# -------------------------------------------------------------------------------------------------
echo
echo `date`
echo "Checking parameters ..."
# -------------------------------------------------------------------------------------------------
if [ -n "$SUPPLIED_NAME" ]
then

    if [ ${#SUPPLIED_NAME} -gt 16 ]
    then
        echo "ERROR - The web-app name length has to be 16 characters or less."
        usage
        exit 1
    fi

    WEB_APP_NAME=$SUPPLIED_NAME
else

    WEB_APP_NAME=$(date +%Y%m%d-%H%M%S)
fi

# Convert to lowercase to make name more usable as a MySQL
# database name/username and as a vhost name.
WEB_APP_NAME="${WEB_APP_NAME,,}"

# -------------------------------------------------------------------------------------------------
echo
echo `date`
echo "Run playbook to delete vhost and web-app code ..."
# -------------------------------------------------------------------------------------------------
ansible-playbook --extra-vars "target=localhost web_app_name=${WEB_APP_NAME} web_app_user=${WEB_APP_USER}" /opt/fp-server-tools/playbooks/debian-10/delete-vhost.yml

# -------------------------------------------------------------------------------------------------
echo
echo `date`
echo "Finished - the web-app ${WEB_APP_NAME} has been deleted."
# -------------------------------------------------------------------------------------------------
exit 0
