---
- hosts: "{{ target | default('no_hosts')}}"

  tasks:
    # Check variables have been set.
    - fail:
        msg: "The variable web_app_name needs to be set."
      when:  web_app_name is not defined

    - fail:
        msg: "The variable web_app_user needs to be set."
      when:  web_app_user is not defined

    - name: Delete the directory holding the web-app code
      file:
        path: /home/{{ web_app_user }}/web-apps/{{ web_app_name }}
        state: absent

    # Note we are not restarting apache2 here as it will be restarted after enabling the site.
    - name: Delete vhost file
      file:
        path: /etc/apache2/sites-available/{{ web_app_name }}.conf
        state: absent

    - name: Disable the site by deleting the symlink
      file:
        path: /etc/apache2/sites-enabled/{{ web_app_name }}.conf
        state: absent
      notify:
          - restart apache2

    - name: Delete the pool files then restart the required version of php-fpm
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/php/5.6/fpm/pool.d/{{ web_app_name }}.conf
        - /etc/php/7.0/fpm/pool.d/{{ web_app_name }}.conf
        - /etc/php/7.1/fpm/pool.d/{{ web_app_name }}.conf
        - /etc/php/7.2/fpm/pool.d/{{ web_app_name }}.conf
        - /etc/php/7.3/fpm/pool.d/{{ web_app_name }}.conf
      notify:
        - restart php5.6-fpm
        - restart php7.0-fpm
        - restart php7.1-fpm
        - restart php7.2-fpm
        - restart php7.3-fpm

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart php5.6-fpm
      service: name=php5.6-fpm state=restarted
    - name: restart php7.0-fpm
      service: name=php7.0-fpm state=restarted
    - name: restart php7.1-fpm
      service: name=php7.1-fpm state=restarted
    - name: restart php7.2-fpm
      service: name=php7.2-fpm state=restarted
    - name: restart php7.3-fpm
      service: name=php7.3-fpm state=restarted
