---
- hosts: "{{ target | default('no_hosts')}}"

  tasks:
    - name: Set php on the command line to use a version which drush is compatible with.
      alternatives:
        name: php
        path: /usr/bin/php7.1
  vars:
#    composer_version: "1.8.4"
    drush_version: "8.2.3"

  roles:
    # These roles have been chosen as they allow us to set the version.  This means that
    # the version will be consistent and we should not be caught out by this playbook
    # installing a latest version which has breaking changes.
#    - net2grid.composer
    - mejo-.drush
