---
- hosts: "{{ target | default('no_hosts')}}"
  tasks:
    - package:
        name:
          - php5.6-xdebug
          - php7.0-xdebug
          - php7.1-xdebug
          - php7.2-xdebug
          - php-xdebug
        state: present

    - blockinfile:
        path: /etc/php/5.6/mods-available/xdebug.ini
        marker: "// {mark} ANSIBLE MANAGED BLOCK"
        block: |
          xdebug.remote_enable = 1

    - blockinfile:
        path: /etc/php/7.0/mods-available/xdebug.ini
        marker: "// {mark} ANSIBLE MANAGED BLOCK"
        block: |
          xdebug.remote_enable = 1

    - blockinfile:
        path: /etc/php/7.1/mods-available/xdebug.ini
        marker: "// {mark} ANSIBLE MANAGED BLOCK"
        block: |
          xdebug.remote_enable = 1

    - blockinfile:
        path: /etc/php/7.2/mods-available/xdebug.ini
        marker: "// {mark} ANSIBLE MANAGED BLOCK"
        block: |
          xdebug.remote_enable = 1

    - blockinfile:
        path: /etc/php/7.3/mods-available/xdebug.ini
        marker: "// {mark} ANSIBLE MANAGED BLOCK"
        block: |
          xdebug.remote_enable = 1
